sudo: required
services:
  - docker

before_install:
  - docker build -t xraynii/reactdocker -f Dockerfile.dev .

script:
  - docker run xraynii/reactdocker yarn coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-198994188279"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
