version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "test"]